version: "3.6"

services:

  rmonnetapp:
    image: rmonnetapp:latest
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - .env
    extra_hosts:
#      capifcore: 192.168.202.35
       capifcore: 10.161.1.117
